[package]
name = "slime"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = { version = "0.9.0", features = ["canvas", "tokio"] }
iced_native = "0.10.3"
vector2d = "2.2.0"
xorshift = "0.1.3"
